;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/Game
DestinationPath=Content/Localization/Game
ManifestName=Game.manifest
ArchiveName=Game.archive
PortableObjectName=Game.po
NativeCulture=ru
CulturesToGenerate=ru

[GatherTextStep0]
CommandletClass=GatherTextFromSource
SearchDirectoryPaths=Source/
SearchDirectoryPaths=Config/
ExcludePathFilters=Config/Localization/*
FileNameFilters=*.h
FileNameFilters=*.cpp
FileNameFilters=*.ini
ShouldGatherFromEditorOnlyData=false

[GatherTextStep1]
CommandletClass=GatherTextFromAssets
IncludePathFilters=Content/*
ExcludePathFilters=Content/Localization/*
ExcludePathFilters=Content/Developers/*
PackageFileNameFilters=*.umap
PackageFileNameFilters=*.uasset
bFixBroken=false
ShouldGatherFromEditorOnlyData=false
bSkipGatherCache=false

[GatherTextStep2]
CommandletClass=GenerateGatherManifest

[GatherTextStep3]
CommandletClass=GenerateGatherArchive
bPurgeOldEmptyEntries=true

[GatherTextStep4]
CommandletClass=InternationalizationExport
bImportLoc=true

[GatherTextStep5]
CommandletClass=GenerateTextLocalizationResource
ResourceName=Game.locres

[GatherTextStep6]
CommandletClass=InternationalizationExport
bExportLoc=true

